apiVersion: v1
kind: Pod
metadata:
  name: python-app
  labels:
    app: app
spec:
  containers:
    - name: python-app
      image: tiangolo/uwsgi-nginx-flask:python3.8
      ports:
        - containerPort: 80
